baseURL = "https://seoulsaram.org"
title = "Sungjoon Moon's Website"
languageCode = "en-us"
theme = "hugo-theme-fs"
disablePathToLower = true
disableHugoGeneratorInject = true
capitalizeListTitles = false
enableRobotsTXT = true
timeZone = "Asia/Seoul"

[params]
  author = "Sungjoon Moon"
  description = "Sungjoon Moon's Personal Blog"
  rssTitle = "SEOULSARAM"
  license = "CC BY 4.0"
  licenseUrl = "https://creativecommons.org/licenses/by/4.0/"
  notFoundImage = "/_media/apowerbookaboutnothing.jpg"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.typographer]
  disable = true

[markup.goldmark.extensions.cjk]
  enable = true
  escapedSpace = true

[markup.highlight]
  style = "github-dark"
  codeFences = true
  noClasses = true

[minify]
  minifyOutput = true

[[menu.main]]
  name = "ABOUT"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "RSS"
  url = "/rss.xml"
  weight = 2

[[menu.main]]
  name = "TAGS"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "RESUME"
  url = "/resume.pdf"
  weight = 4

[outputFormats.RSS]
  baseName = "rss"

[outputs]
  home = ["HTML", "RSS"]
