baseURL = "https://seoulsaram.org"
title = "Sungjoon Moon's Website"
languageCode = "en-us"
theme = "hugo-theme-fs"
disablePathToLower = true
disableHugoGeneratorInject = true
capitalizeListTitles = false
enableRobotsTXT = true
timeZone = "Asia/Seoul"

[params]
  author = "Sungjoon Moon"
  description = "Sungjoon Moon's Personal Blog"
  rssTitle = "SEOULSARAM"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.typographer]
  disable = true

[markup.highlight]
  style = "github"
  codeFences = true
  noClasses = true

[minify]
  minifyOutput = true

[[menu.main]]
  name = "ABOUT"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "RSS"
  url = "/rss.xml"
  weight = 2

[[menu.main]]
  name = "TAGS"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "RESUME"
  url = "/resume.pdf"
  weight = 4

[outputFormats.RSS]
  baseName = "rss"

[outputs]
  home = ["HTML", "RSS"]
